# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
r = Role.create!([{name: "admin"}])

u = User.create!([{name: "Administrator", username: "admin", password: "admin", password_confirmation: "admin", role_id: 1}])

DogState.create!(name: "Healthy")
DogState.create!(name: "Adopted")
DogState.create!(name: "Unhealthy or Injured")
DogState.create!(name: "Recovery")
DogState.create!(name: "Sleep")

Breed.create!(name: "Beagle")
Breed.create!(name: "Aspin")
Breed.create!(name: "Chihuahua")
Breed.create!(name: "Pomeranian")
Breed.create!(name: "Shih Tzu")
Breed.create!(name: "Labrador")
Breed.create!(name: "Golden Retriever")
Breed.create!(name: "German Shepherd")
Breed.create!(name: "Belgian Mallanois")
Breed.create!(name: "Siberian Husky")
Breed.create!(name: "Alaskan Malamute")
Breed.create!(name: "American Bulldog")
Breed.create!(name: "French Bulldog")
Breed.create!(name: "English Bulldog")
Breed.create!(name: "Pug")
Breed.create!(name: "Rottweiler")
Breed.create!(name: "St. Bernard")
Breed.create!(name: "Corgi")
Breed.create!(name: "Border Collie")
Breed.create!(name: "Youkshire Terrier")
Breed.create!(name: "Bichon Frise")
Breed.create!(name: "Poddle")
Breed.create!(name: "Duchshund")
Breed.create!(name: "Bull Mastiff")
Breed.create!(name: "Jack Russel Terrier")
Breed.create!(name: "Schnauzer")
Breed.create!(name: "Greatdane")
Breed.create!(name: "Dalmatian")
Breed.create!(name: "Japanese Spitz")
Breed.create!(name: "Boston Terrier")
Breed.create!(name: "Dobermann")
Breed.create!(name: "Cocker Spaniel")
Breed.create!(name: "Mini Pincher")
Breed.create!(name: "Lhasa Apso")
Breed.create!(name: "Pekingese")
Breed.create!(name: "Scottish Terrier")

Place.create!(name: "Airport")
Place.create!(name: "Alegria")
Place.create!(name: "Alta Vista")
Place.create!(name: "Bagong")
Place.create!(name: "Bagong Buhay")
Place.create!(name: "Bantigue")
Place.create!(name: "Barangay 1")
Place.create!(name: "Barangay 10")
Place.create!(name: "Barangay 11")
Place.create!(name: "Barangay 12")
Place.create!(name: "Barangay 13")
Place.create!(name: "Barangay 14")
Place.create!(name: "Barangay 15")
Place.create!(name: "Barangay 16")
Place.create!(name: "Barangay 17")
Place.create!(name: "Barangay 18")
Place.create!(name: "Barangay 19")
Place.create!(name: "Barangay 2")
Place.create!(name: "Barangay 20")
Place.create!(name: "Barangay 21")
Place.create!(name: "Barangay 22")
Place.create!(name: "Barangay 23")
Place.create!(name: "Barangay 24")
Place.create!(name: "Barangay 25")
Place.create!(name: "Barangay 26")
Place.create!(name: "Barangay 27")
Place.create!(name: "Barangay 28")
Place.create!(name: "Barangay 29")
Place.create!(name: "Barangay 3")
Place.create!(name: "Barangay 4")
Place.create!(name: "Barangay 5")
Place.create!(name: "Barangay 6")
Place.create!(name: "Barangay 7")
Place.create!(name: "Barangay 8")
Place.create!(name: "Barangay 9")
Place.create!(name: "Batuan")
Place.create!(name: "Bayog")
Place.create!(name: "Biliboy")
Place.create!(name: "Borok")
Place.create!(name: "Cabaon-an")
Place.create!(name: "Cabintan")
Place.create!(name: "Cabulihan")
Place.create!(name: "Cagbuhangin")
Place.create!(name: "Camp Downes")
Place.create!(name: "Can-adieng")
Place.create!(name: "Can-untog")
Place.create!(name: "Catmon")
Place.create!(name: "Cogon Combado")
Place.create!(name: "Concepcion")
Place.create!(name: "Curva")
Place.create!(name: "Danao")
Place.create!(name: "Danhug5")
Place.create!(name: "Dayhagan")
Place.create!(name: "Dolores")
Place.create!(name: "Domonar1")
Place.create!(name: "Don Felipe Larrazabal")
Place.create!(name: "Don Potenciano Larrazabal")
Place.create!(name: "Doña Feliza Z. Mejia")
Place.create!(name: "Donghol")
Place.create!(name: "Esperanza")
Place.create!(name: "Gaas")
Place.create!(name: "Green Valley")
Place.create!(name: "Guintigui-an")
Place.create!(name: "Hibunawon")
Place.create!(name: "Hugpa")
Place.create!(name: "Ipil")
Place.create!(name: "Juaton")
Place.create!(name: "Kadaohan")
Place.create!(name: "Labrador")
Place.create!(name: "Lao")
Place.create!(name: "Leondon")
Place.create!(name: "Libertad")
Place.create!(name: "Liberty")
Place.create!(name: "Licuma")
Place.create!(name: "Liloan")
Place.create!(name: "Linao")
Place.create!(name: "Luna")
Place.create!(name: "Mabato")
Place.create!(name: "Mabin")
Place.create!(name: "Macabug")
Place.create!(name: "Magaswi")
Place.create!(name: "Mahayag")
Place.create!(name: "Mahayahay")
Place.create!(name: "Manlilinao")
Place.create!(name: "Margen")
Place.create!(name: "Mas-in")
Place.create!(name: "Matica-a")
Place.create!(name: "Milagro")
Place.create!(name: "Monterico")
Place.create!(name: "Nasunogan")
Place.create!(name: "Naungan")
Place.create!(name: "Nueva Sociedad")
Place.create!(name: "Nueva Vista")
Place.create!(name: "Patag")
Place.create!(name: "Punta")
Place.create!(name: "Quezon, Jr.")
Place.create!(name: "Rufina M. Tan")
Place.create!(name: "Sabang Bao")
Place.create!(name: "Salvacion")
Place.create!(name: "San Antonio")
Place.create!(name: "San Isidro")
Place.create!(name: "San Jose")
Place.create!(name: "San Juan")
Place.create!(name: "San Pablo")
Place.create!(name: "San Vicente")
Place.create!(name: "Santo Niño")
Place.create!(name: "Sumangga")
Place.create!(name: "Tambulilid")
Place.create!(name: "Tongonan")
Place.create!(name: "Valencia")