# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
r = Role.create!([{name: "admin"}])

u = User.create!([{name: "Administrator", username: "admin", password: "admin", password_confirmation: "admin", role_id: 1}])

DogState.create!(name: "Healthy")
DogState.create!(name: "Adopted")
DogState.create!(name: "Unhealthy or Injured")
DogState.create!(name: "Recovery")
DogState.create!(name: "Sleep")

Breed.create!(name: "Beagle")
Breed.create!(name: "Aspin")
Breed.create!(name: "Chihuahua")
Breed.create!(name: "Pomeranian")
Breed.create!(name: "Shih Tzu")
Breed.create!(name: "Labrador")
Breed.create!(name: "Golden Retriever")
Breed.create!(name: "German Shepherd")
Breed.create!(name: "Belgian Mallanois")
Breed.create!(name: "Siberian Husky")
Breed.create!(name: "Alaskan Malamute")
Breed.create!(name: "American Bulldog")
Breed.create!(name: "French Bulldog")
Breed.create!(name: "English Bulldog")
Breed.create!(name: "Pug")
Breed.create!(name: "Rottweiler")
Breed.create!(name: "St. Bernard")
Breed.create!(name: "Corgi")
Breed.create!(name: "Border Collie")
Breed.create!(name: "Youkshire Terrier")
Breed.create!(name: "Bichon Frise")
Breed.create!(name: "Poddle")
Breed.create!(name: "Duchshund")
Breed.create!(name: "Bull Mastiff")
Breed.create!(name: "Jack Russel Terrier")
Breed.create!(name: "Schnauzer")
Breed.create!(name: "Greatdane")
Breed.create!(name: "Dalmatian")
Breed.create!(name: "Japanese Spitz")
Breed.create!(name: "Boston Terrier")
Breed.create!(name: "Dobermann")
Breed.create!(name: "Cocker Spaniel")
Breed.create!(name: "Mini Pincher")
Breed.create!(name: "Lhasa Apso")
Breed.create!(name: "Pekingese")
Breed.create!(name: "Scottish Terrier")